version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_local
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - posgres_data:/var/lib/postgresql/data

volumes:
  posgres_data: