version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_local
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - posgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    build: ./api  # Ruta donde está tu script y Dockerfile
    container_name: api_service
    restart: always
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgresql://admin:adminpasswd@db:5432/H2-lab
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - /home/icehot03/H2_lab/H2-DB/api:/app

networks:
  my_network:
    driver: bridge

volumes:
  posgres_data:
    driver: local


